### ISSUE TITLE
bump release version in bitrise.yml 

### ISSUE THREAD

**Issue by mabenhaddada** [LucianoPAlmeida/bitrise-step-swift-environment-variable-injector#10]
https://github.com/LucianoPAlmeida/bitrise-step-swift-environment-variable-injector/blob/d476ab9dbd4c7cbb5fb8cc6362d6969f8c659049/bitrise.yml#L8

This should be 0.1.3 I think

**Comment by mabenhaddada** [comment]
When I run the step on Bitrise, the v0.1.2 is selected which run `echo variable-injector --file ${files} $VERBOSE $IGNORE_PARAM` instead of `variable-injector --file ${files} $VERBOSE $IGNORE_PARAM`

I know this because I this line in the log :
```
<<some logs>>
.
.
inflating: x86_64-apple-macosx/release/variable_injector.build/main.swift.o  
inflating: x86_64-apple-macosx/release/variable_injector.build/output-file-map.json  
inflating: x86_64-apple-macosx/release/variable_injector.build/variable_injector.d  
inflating: x86_64-apple-macosx/release/variable_injector.build/master.swiftdeps  
~/git
variable-injector --file /Users/vagrant/git/PROJECT_DIR/CI.swift --verbose --ignore NONE 
```

Should be below snippet in case we run :  `variable-injector --file ${files} $VERBOSE $IGNORE_PARAM` instead of `variable-injector --file ${files} $VERBOSE $IGNORE_PARAM` (last line should not be shown)

```
<<some logs>>
.
.
inflating: x86_64-apple-macosx/release/variable_injector.build/main.swift.o  
inflating: x86_64-apple-macosx/release/variable_injector.build/output-file-map.json  
inflating: x86_64-apple-macosx/release/variable_injector.build/variable_injector.d  
inflating: x86_64-apple-macosx/release/variable_injector.build/master.swiftdeps  
~/git
```

I git cloned the step an `bitrise run test`. works fine because the HEAD is pointing to the latest commit. But I think that the latest update of the step on Bitrise still pointing on `v0.1.2` tag !

Running with `echo` results on injection fail and the File.swift still unchanged

**Comment by mabenhaddada** [comment]
Just forked your repo, tagged a new release with v0.1.3 and bumped BITRISE_STEP_VERSION to 0.1.3. this leads the step to work as a charm : [Fork: test fix of BITRISE_STEP_VERSION](https://github.com/mounou19/bitrise-step-swift-environment-variable-injector)

**Comment by LucianoPAlmeida** [comment]
0.1.3 should be available on bitrise. Can you verify and close?

**Comment by mabenhaddada** [comment]
Works fine 👌
Thank you
