### ISSUE TITLE
404 Not Found Error when running Step 

### ISSUE THREAD

**Issue by harrywombat** [LucianoPAlmeida/bitrise-step-swift-environment-variable-injector#11]
Hi there, I've just added in this Bitrise step but I'm having trouble running it.

The error logs aren't clear as to what is happening. I've got all the secrets setup in Bitrise and the variables in my project, and I have the step included.

Is the 404 saying that the actual step source code isn't being downloaded from github? 
Or is it 404 because the variables aren't found?
Or because of something else?

Any help would be greatly appreciated, thank you.

<img width="1347" alt="Screenshot 2024-01-19 at 11 17 06" src="https://github.com/LucianoPAlmeida/bitrise-step-swift-environment-variable-injector/assets/74178376/e124b406-8bd9-43b0-bed5-af94eb569ca7">

<img width="388" alt="Screenshot 2024-01-19 at 11 18 20" src="https://github.com/LucianoPAlmeida/bitrise-step-swift-environment-variable-injector/assets/74178376/1d2caa0c-3ee1-408f-8dfd-157f98792b7e">

**Comment by LucianoPAlmeida** [comment]
This version is incorrect 
`- variable_injector_version: 0.1.3`

This doesn't even exist under [releases](https://github.com/LucianoPAlmeida/variable-injector/releases)
Try  `- variable_injector_version: 0.3.7`
