### ISSUE TITLE
'_InternalSwiftSyntaxParser' not compatible with the version of SwiftSyntax on Xcode 13

### ISSUE THREAD

**Issue by vitasuper** [LucianoPAlmeida/bitrise-step-swift-environment-variable-injector#3]
Hi @LucianoPAlmeida!

We use `Swift Environment Variable Injector` on Bitrise as a workflow step and it works fine on Xcode 12.5.x. After switching the Xcode version on our build machine to Xcode 13.0.x we received the following error:

```  
// ...

inflating: x86_64-apple-macosx/release/ArgumentParser.build/Parsing/InputOrigin.swift.o  
  inflating: x86_64-apple-macosx/release/ArgumentParser.build/Parsing/Name.swift.o  
   creating: x86_64-apple-macosx/release/variable-injector.dSYM/Contents/Resources/
  inflating: x86_64-apple-macosx/release/variable-injector.dSYM/Contents/Info.plist  
  inflating: x86_64-apple-macosx/release/SwiftSyntax.build/gyb_generated/syntax_nodes/SyntaxNodes.swift.o  
  inflating: x86_64-apple-macosx/release/SwiftSyntax.build/gyb_generated/syntax_nodes/SyntaxTypeNodes.swift.o  
  inflating: x86_64-apple-macosx/release/SwiftSyntax.build/gyb_generated/syntax_nodes/SyntaxExprNodes.swift.o  
  inflating: x86_64-apple-macosx/release/SwiftSyntax.build/gyb_generated/syntax_nodes/SyntaxStmtNodes.swift.o  
  inflating: x86_64-apple-macosx/release/SwiftSyntax.build/gyb_generated/syntax_nodes/SyntaxPatternNodes.swift.o  
  inflating: x86_64-apple-macosx/release/SwiftSyntax.build/gyb_generated/syntax_nodes/SyntaxDeclNodes.swift.o  
   creating: x86_64-apple-macosx/release/variable-injector.dSYM/Contents/Resources/DWARF/
  inflating: x86_64-apple-macosx/release/variable-injector.dSYM/Contents/Resources/DWARF/variable-injector  
~/git
Error: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
```

Related info:
* Xcode version: 13.0.x
* Build machine: macOS 11.4 (Big Sur)
* `Swift Environment Variable Injector` (bitrise step) version: 0.1.1
* `Swift Variable Injector Version` version: 0.3.4

I noticed an issue here - https://github.com/LucianoPAlmeida/variable-injector/issues/17 and think they might be similar. 

Please let me know if I can provide more information. Thank you for looking into it!

**Comment by LucianoPAlmeida** [comment]
Hey @vitasuper =]
Yeah, unfortunately we have to do this(update version SwiftSyntax and consequently libSyntax) every major version of Swift. 
I'll try to do that as soon as possible

**Comment by vitasuper** [comment]
Awesome! Thank you for the quick reply and for taking care of it @LucianoPAlmeida

**Comment by vitasuper** [comment]
Hey @LucianoPAlmeida, hope everything is going well! Do we have any updates on this? We are technically blocked by this step to generate an iOS 15 build using the Xcode beta on Bitrise build machine. Thank you!

**Comment by LucianoPAlmeida** [comment]
Hi @vitasuper, 
I was waiting an official release of SwiftSyntax for 5.5, as you can see https://github.com/apple/swift-syntax/releases, right now there are just developer snapshots. And as you can see on the previous 5.4 update https://github.com/LucianoPAlmeida/variable-injector/pull/21/files, in order to release a new version the main modification is to update swift syntax version... it may be possible to generate a version targeted on the version of SwiftSyntax that is used by the beta toolchain, but it would mean that we would have to do another release once the tag 5.5 on SwiftSyntax

**Comment by LucianoPAlmeida** [comment]
Tag https://github.com/LucianoPAlmeida/variable-injector/releases/tag/0.3.5 is out! Can you please test if that is fixed? Thanks :)

**Comment by LucianoPAlmeida** [comment]
Closing, but feel free to reopen if there are still issues

**Comment by vitasuper** [comment]
Thank you @LucianoPAlmeida! Will try and get back to you soon!

**Comment by MarekSlaninka** [comment]
Hi @LucianoPAlmeida, it seems that with Xcode 13.3 this is once again broken. I tried to update SwiftSyntax to 0.50600.1, but then there was an error in code, so build didn't go through
