### ISSUE TITLE
Issue with Bitrise when using step version 0.1.2

### ISSUE THREAD

**Issue by jakunico** [LucianoPAlmeida/bitrise-step-swift-environment-variable-injector#9]
Hi there!

We are having issues using this in Bitrise. We are using it to load a secret API key into one of our Swift files. Surprisingly the tool was working just fine and it did start failing without any update from our side to either the project's code or the Bitrise.yml.

Wondering if folks that use this tool on Bitrise noticed any issue (indicating a regression) or if it continued working just fine (indicating an issue with our set up).

Things we have checked:

- Path to the file is correct
- Turn on "verbose" mode (does not print anything)

Any tips on how we can debug this would be appreciated. Attaching a few screenshots below for reference.

Thanks!

![image](https://user-images.githubusercontent.com/1474405/198059947-bf3a7fdf-db60-4e70-9114-425c058bfd65.png)
![image](https://user-images.githubusercontent.com/1474405/198061126-61397ede-3ad8-4590-85e3-7a58d990ec81.png)
![image](https://user-images.githubusercontent.com/1474405/198061217-76439899-c2f1-41e8-a265-bdd08aeac75c.png)

**Comment by LucianoPAlmeida** [comment]
We recently updated step version to 0.1.2, I see in your screenshot you are using it. But you can try 0.1.1 to test

**Comment by jakunico** [comment]
Thanks Luciano, I can't seem to find how to downgrade to `0.1.1`, only allows to select `0.x.x` and `0.1.x` through the GUI:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/1474405/198097057-e1522780-dae7-4ef4-a588-7d67ac649459.png">

Maybe is there some way in the Bitrise.yml file to specify this?

**Comment by gaborTachtler** [comment]
Hey @jakunico!
In the bitrise yaml file, add @0.1.1 to the step name:
![Screenshot 2022-10-26 at 20 26 28](https://user-images.githubusercontent.com/42982276/198106814-44654521-36f1-4042-a6bc-93836dd709b0.png)

**Comment by jakunico** [comment]
Thank you folks, that fixed the issue!
So seems like something is wrong with `0.1.2`.

**Comment by LucianoPAlmeida** [comment]
That is wired, 0.1.2 seems to be working for for others ...

**Comment by jakunico** [comment]
Just did another test, reverted back to `0.1.2` and the build is indeed not passing.

**Comment by LucianoPAlmeida** [comment]
> Just did another test, reverted back to `0.1.2` and the build is indeed not passing.

Can you share the logs of the step execution with 0.1.2? Of course what is possible to share. I want to see what is happening with shell execution. It should curl a package, extract, cp some file to places and execute the binary

**Comment by mabenhaddada** [comment]
Hello,

Well, I also got an issue injecting my env variables to the project using new `0.1.2` version of the swift-env-var-injector Bitrise step. tested by setting both `0.3.6` & `0.3.7` in the _**Swift Variable Injector Version**_ field

I downgraded back to `v0.1.1` with `0.3.6` in the _**Swift Variable Injector Version**_ field and the vars are injected back correctly.

Not sure why the `0.1.2` is not working as expected ...

**Comment by LucianoPAlmeida** [comment]
Can you try with 0.1.3

**Comment by LucianoPAlmeida** [comment]
Issue should be fixed that version

**Comment by Ghassen-Ferchichi** [comment]
I just did a test with 0.1.3 and everything seems working fine 🔥 Thanks a lot for the fix, YOU ROCK

**Comment by LucianoPAlmeida** [comment]
Awesome, thanks for the verification.
Closing this
